//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullHouseWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_House()
        {
            this.tbl_Image = new HashSet<tbl_Image>();
        }
    
        public int houseID { get; set; }
        public string emailAdmin { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> roomNumber { get; set; }
        public Nullable<bool> furniture { get; set; }
        public Nullable<double> acreage { get; set; }
        public Nullable<int> floor { get; set; }
        public bool rentStatus { get; set; }
        public Nullable<int> areaID { get; set; }
        public string houseNumber { get; set; }
        public string houseStreet { get; set; }
        public string otherDetails { get; set; }
    
        public virtual tbl_Admin tbl_Admin { get; set; }
        public virtual tbl_Area tbl_Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Image> tbl_Image { get; set; }
    }
}
