//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullHouseWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Area()
        {
            this.tbl_House = new HashSet<tbl_House>();
        }
    
        public int areaID { get; set; }
        public string areaName { get; set; }
        public Nullable<int> districtID { get; set; }
    
        public virtual tbl_District tbl_District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_House> tbl_House { get; set; }
    }
}
